"""create workout_set and pr tables

Revision ID: 2635eec6d1fb
Revises: 37435dd1594c
Create Date: 2026-06-18 19:36:53.155415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2635eec6d1fb'
down_revision: Union[str, Sequence[str], None] = '37435dd1594c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workoutset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['sessionexercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_def_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_def_id'], ['exercisedefinition.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['workoutset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr')
    op.drop_table('workoutset')
    # ### end Alembic commands ###
