"""create workout and workout_exercise tables

Revision ID: 88f92c578b38
Revises: 76798456f8e5
Create Date: 2026-06-18 19:21:02.828638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88f92c578b38'
down_revision: Union[str, Sequence[str], None] = '76798456f8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('program_day', sa.Integer(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workoutexercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_def_id', sa.Integer(), nullable=False),
    sa.Column('exercise_order', sa.Integer(), nullable=False),
    sa.Column('planned_sets', sa.Integer(), nullable=False),
    sa.Column('planned_reps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_def_id'], ['exercisedefinition.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workoutexercise')
    op.drop_table('workout')
    # ### end Alembic commands ###
