"""add date field to pr table

Revision ID: b9726d529b71
Revises: 2635eec6d1fb
Create Date: 2026-07-01 16:28:28.131256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = 'b9726d529b71'
down_revision: Union[str, Sequence[str], None] = '2635eec6d1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pr', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pr', 'date')
    # ### end Alembic commands ###
